# Generated by Django 5.2.2 on 2025-06-08 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ispb', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PixMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_to_end_id', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagador_nome', models.CharField(max_length=100)),
                ('pagador_cpf_cnpj', models.CharField(max_length=14)),
                ('pagador_ispb', models.CharField(max_length=8)),
                ('pagador_agencia', models.CharField(max_length=10)),
                ('pagador_conta', models.CharField(max_length=20)),
                ('pagador_tipo_conta', models.CharField(max_length=10)),
                ('recebedor_nome', models.CharField(max_length=100)),
                ('recebedor_cpf_cnpj', models.CharField(max_length=14)),
                ('recebedor_ispb', models.CharField(max_length=8)),
                ('recebedor_agencia', models.CharField(max_length=10)),
                ('recebedor_conta', models.CharField(max_length=20)),
                ('recebedor_tipo_conta', models.CharField(max_length=10)),
                ('campo_livre', models.TextField(blank=True)),
                ('tx_id', models.CharField(max_length=100)),
                ('data_pagamento', models.DateTimeField()),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='streaming.streamsession')),
            ],
        ),
    ]
